apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deppops
  namespace: deppops
  labels:
    app: deppops
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: deppops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deppops
            port:
              name: http
