name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write # for cosign

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v14
        with:
          name: dhbw-ma-tinf23ai1-devops
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build container
        run: nix build .#container

      - name: Login to GitHub Container Registry (skopeo)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | nix develop --command skopeo login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Login to GitHub Container Registry (cosign)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | nix develop --command cosign login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine Image Name
        id: image_name
        run: |
          IMAGE_NAME=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/deppops
          TAG=$(nix eval --raw ".#packages.x86_64-linux.container.imageTag")
          echo "IMAGE_WITH_TAG=${IMAGE_NAME}:${TAG}" >> $GITHUB_OUTPUT

      - name: Generate Vulnerability Reports
        run: |
          REPORTS_DIR=$(nix develop --command nu ci/vulnscan.nu)
          echo "REPORTS_DIR=$REPORTS_DIR" >> $GITHUB_ENV

      - name: Push with skopeo
        run: |
          nix develop --command skopeo copy docker-archive:result docker://${{ steps.image_name.outputs.IMAGE_WITH_TAG }}

      - name: Get Image Digest
        id: digest
        run: |
          DIGEST=$(nix develop --command skopeo inspect docker://${{ steps.image_name.outputs.IMAGE_WITH_TAG }} | jq -r '.Digest')
          echo "IMAGE_DIGEST=${DIGEST}" >> $GITHUB_OUTPUT
          IMAGE_NAME_PARTS=$(echo "${{ steps.image_name.outputs.IMAGE_WITH_TAG }}" | cut -d: -f1)
          echo "IMAGE_WITH_DIGEST=${IMAGE_NAME_PARTS}@${DIGEST}" >> $GITHUB_OUTPUT

      - name: Attach Vulnerability Reports
        run: |
          nix develop --command nu ci/attach-sbom.nu ${{ env.REPORTS_DIR }} ${{ steps.digest.outputs.IMAGE_WITH_DIGEST }}

      - name: Sign container
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: nix develop --command nu ci/sign.nu ${{ steps.digest.outputs.IMAGE_WITH_DIGEST }}
